openapi: 3.1.0
info:
  title: Cast Data Type Schema
  version: 1.0.0
  description: 데이터 타입 변환 스키마 정의

components:
  schemas:
    cast_data_type:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: cast_data_type }
        parameters:
          type: object
          required:
            - columns
          properties:
            columns:
              $ref: '../definitions.yml#/components/schemas/data_schema'
          description: 함수 매개변수
