openapi: 3.1.0
info:
  title: Read CSV Schema
  version: 1.0.0
  description: CSV 파일을 읽는 스키마

components:
  schemas:
    read_csv:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: read_csv }
        parameters:
          $ref: '../definitions.yml#/components/schemas/datasource_read_csv'
