openapi: 3.1.0
info:
  title: Fill Random Float Schema
  version: 1.0.0
  description: 랜덤 실수값을 채우는 스키마

components:
  schemas:
    fill_random_float:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: fill_random_float }
        parameters:
          type: object
          required:
            - output_columns
          properties:
            output_columns:
              $ref: '../definitions.yml#/components/schemas/column_name_or_list'
            min:
              type: number
            max:
              type: number
            seed:
              type: integer
