openapi: 3.1.0
info:
  title: Apply Conditions Schema
  version: 1.0.0
  description: 조건에 따라 값을 적용하는 스키마

components:
  schemas:
    apply_conditions:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: apply_conditions }
        parameters:
          type: object
          required:
            - output_column
            - conditions
          properties:
            data_type:
              type: string
              enum: [string, int, float]
            output_column:
              $ref: '../definitions.yml#/components/schemas/column_name'
            default_value:
              $ref: '../definitions.yml#/components/schemas/value'
            conditions:
              type: array
              items:
                type: object
                properties:
                  value:
                    $ref: '../definitions.yml#/components/schemas/value'
                  condition:
                    $ref: '../definitions.yml#/components/schemas/condition'
