openapi: 3.1.0
info:
  title: Orderby Schema
  version: 1.0.0
  description: 데이터를 정렬하는 스키마

components:
  schemas:
    orderby:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: orderby }
        parameters:
          type: object
          required:
            - by
          properties:
            by:
              $ref: '../definitions.yml#/components/schemas/sort_order'
            na_position:
              type: string
              enum: [first, last]
