openapi: 3.1.0
info:
  title: SHA-2 Schema
  version: 1.0.0
  description: SHA-2 해시 함수를 사용한 암호화 스키마

components:
  schemas:
    sha2:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: sha2 }
        parameters:
          type: object
          required:
            - columns
          properties:
            columns:
              $ref: '../definitions.yml#/components/schemas/column_name_or_list'
            length:
              type: integer
              enum: [224, 256, 384, 512]
            salt:
              type: string
            salt_position:
              type: string
              enum: [prefix, suffix]
            encoding:
              type: string
              enum: [hex_lower, hex_upper, base64]
            output_columns:
              $ref: '../definitions.yml#/components/schemas/column_name_or_list'
