openapi: 3.1.0
info:
  title: Categorize By Equal Width Schema
  version: 1.0.0
  description: 동일한 너비로 구간을 나누어 카테고리화하는 스키마

components:
  schemas:
    categorize_by_equal_width:
      type: object
      required:
        - function
        - parameters
      properties:
        function: { const: categorize_by_equal_width }
        parameters:
          type: object
          required:
            - columns
          properties:
            columns:
              $ref: '../definitions.yml#/components/schemas/column_name_or_list'
            bins:
              type: integer
              minimum: 2
            labels:
              type: array
              items: { type: string }
            exclude_values:
              $ref: '../definitions.yml#/components/schemas/exclude_values'
            output_columns:
              $ref: '../definitions.yml#/components/schemas/column_name_or_list'
